name: terraform-apply
description: Apply terraform plan
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend configs to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""
  variables:
    description: Variable definitions
    required: false
  var:
    description: Comma separated list of vars to set, e.g. 'foo=bar'
    required: false
    default: ""
    deprecationMessage: Use the variables input instead.
  var_file:
    description: List of var file paths, one per line
    required: false
    default: ""
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: 0
  label:
    description: A friendly name for this plan
    required: false
    default: ""
  auto_approve:
    description: Automatically approve and apply plan
    default: false
  target:
    description: List of targets to apply against, one per line
    required: false
    default: ""

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:987dcf3c288a803f37a3fb177d95d9d549d37beff8a5bd23c26390e4bae439e2
  entrypoint: /entrypoints/apply.sh

branding:
  icon: globe
  color: purple
